### ISSUE TITLE
Teleportation 2.0: Unifying /tow, /taxi, /tp and /ctp

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#11]
http://trac.sa-mp.nl/lvp/ticket/1453

cake:

> **Source**: ​https://forum.sa-mp.nl/showthread.php?tid=30500&pid=433374#pid433374
> **Idea**: designing the new behavior of the teleportation commands.
> **Proposal**: there will be a single command, "/teleport" or "/tp" for short. When..
> - no arguments are given, a map of San Andreas will be shown with the available fixed teleportation points.
> - a (partial) location name is given, then the player wants to teleport to there.
> - a (partial) player name or full player Id is given, then the player wants to teleport to another player. When..
>   - the player is in the same gang, teleport directly.
>   - they're not in the same gang, ask for permission once per session, teleport after the person being teleported to accepted.
> 
> Teleportation will be completely disabled if the player has been involved near a fight in the last minute. There is a set limit to how often a player can teleport. Both limits are more flexible for VIPs.
> Prices are always determined based on distance, where VIPs will get a discount.

**Comment by LVPJoe** [comment]
For this issue, a possible solution would be one command titled /goto (id/name).

Upon entering this command without any arguments, a dialog would pop up with two options (Location, Player). After selecting the location option, the /t options, now referred to by letter (a-o) rather than number (0-13), will appear with the full name listed such as "LV Police Department" or "Mt. Chiliad Summit". If player was selected instead, it would bring up a text entry box much like when adding exceptions to /lvp access commands currently does. This text entry box would support ids or names. 

If an argument is given, a numeric argument will be interpreted as a player id, an argument one letter in length will refer to a location, and to type a name will require 3 characters or more.
