### ISSUE TITLE
VIP Room Issue

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#129]
If you leave the VIP room by means of a command (e.g. /taxi), you'll be unable to use certain commands (like /inf) and the notice "You must be outside to use this command" will appear. Is it possible to set the same command blockers on the VIP room that are used in other places, like ammu-nation, for example?

**Comment by GodeyLVP** [comment]
Yes, it is possible.
The example given above, that is the ammu-nation, is an interior and can be blocked.

**Comment by HopperLVP** [comment]
See if Problem is Here : 

`// If our player is in the VIP room, they can't call a taxi because OnPlayerInteriorChange sets them back outside the VIP room pickup, so it won't work.
    if(GetPlayerInterior(playerid) == 12)
    {
        ShowBoxForPlayer(playerid, "Step out of the VIP room first.");
        return 1;
    }
`

What if we did 

`// If our player is in the VIP room, they can't call a taxi because OnPlayerInteriorChange sets them back outside the VIP room pickup, so it won't work.
    if(GetPlayerInterior(playerid) == 12)
    {
        ShowBoxForPlayer(playerid, "Step out of the VIP room first.");
        return 0;
    }
`
