### ISSUE TITLE
Finish the new player statistics interface

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#15]
http://trac.sa-mp.nl/lvp/ticket/1483

cake:

> This interface will replace the current userbar + playerinfo (FPS/Ping/PcktLoss) in one neat, minimalistic interface in the down right corner showing kills, deaths, ratio, ping, fps, pcktloss.
> 
> Tickets ​http://trac.sa-mp.nl/lvp/ticket/1479 and ​http://trac.sa-mp.nl/lvp/ticket/1480 will replace the current commands cycling through the userbar helping out new players.
> 
> I'm thinking of showing a small counter somewhere with the amount of people currently participating in minigames, together with a /minigaming command to see who's playing what (currently available for crew only).
> 
> If this feature is done, /my playerinfo will only show other players their fps/ping/loss info (note to self: increase draw distance).
> 
> The Bag of Cash textdraw will have to be moved.

I'm not sure where this is. We should pick it up.

**Comment by ghost** [comment]
Here's what we currently have (remembering that packetloss was removed);

![sa-mp-001](https://cloud.githubusercontent.com/assets/15123289/12791488/38a4cdf4-ca9f-11e5-8c11-bf71aacefd0e.png)

I personally like the interface as it is, however, I do feel that we should look at (re)introducing a listing of commands at the the bottom of the screen. The space is available -- why not utilize it? We could list things like /minigames, /race, /fight, /taxi, /tow, /wanted, etc. 

This really hit home with me today. I happened to be driving around in Los Santos, and came across a stranded player with no vehicle. I watched him running around for a bit, and then he quit. Perhaps he would have stayed ingame if those commands were visible, allowing him to find something else to do.

**Comment by mblokker** [comment]
The story you tell is a very emotional one, but I could also say that since those command hints were removed we had an increase in playercount.

The main reason the commands had to go was because players liked the space more when it was empty, hence the new player stats display is much more simple and transparent.

Also, older players complained of knowing all commands already.

I think the issue you are trying to explain here is known as: https://github.com/LVPlayground/playground/issues/27

**Comment by jadegraaf** [comment]
I agree with @mblokker that the issue here is that upon first join(s) there is a lack of guidance for new players. A skipable tutorial/flow/experience like #27 would help a lot. A small text draw on the screen like "Have you read /help?" wouldn't hurt either. Maybe place it under the minimap? We can always hide it once a player becomes a regular.

**Comment by mblokker** [comment]
I think adding a small textdraw referring to /help and /commands, located under the mini-map can be a good addition, when hidden for regulars.
