### ISSUE TITLE
Spawnweapons multiplier bug

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#162]
This issue has existed for as long as I can remember, but I never thought to report it as it's nothing too important. But still, it's a bug nevertheless.

Supposing I have no spawnweapons, as shown below:

![untitled](https://cloud.githubusercontent.com/assets/15123289/15155879/5e000f1c-16dc-11e6-89b3-b0bc51c3d65c.png)

If I use **/p  [id] spawnweapons 35 1**, I'll be given 2 rounds - where as clearly, I should only receive 1:

![untitled](https://cloud.githubusercontent.com/assets/15123289/15155999/eb3fe1ae-16dc-11e6-8328-73e8ef8cc940.png)

I can re-produce this with any weapon. I used the same command as above, but this time, with the M4:

![untitled](https://cloud.githubusercontent.com/assets/15123289/15156062/3759d9c8-16dd-11e6-8a79-5e00fe6c99d4.png)

**Comment by RussellLVP** [comment]
This actually is expected behaviour, because two and 200 are, respectively, the amount of ammo given when having these weapons as a spawn weapon.

You could improve the message if you wish by modifying SpawnWeaponCommands.pwn:174

I have found another bug, where the command right now is additive rather than overriding. I'll fix that momentarily.
