### ISSUE TITLE
Headshot Script

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#168]
I personally find the outputs, not the functionality, of the script to not align with the professional nature of most of LVP's features and coding. I feel the "headshot" audio is distracting and childish, and it reminds me more of a filterscript from the SA:MP forums than a feature I'd expect on LVP.

**Comment by ghost** [comment]
This functionality, including the "HEADSHOT" audio that is played is defined here: https://github.com/LVPlayground/playground/blob/master/pawn/Features/Deathmatch/DamageManager.pwn

(putting that out there so you can see exactly what we display to players)

Personally, I don't mind this feature, I quite like it - however this isn't about what I like, but more-so, the people that matter most, our players. A number of people have expressed their dislike to this feature as a whole, one of our crew members included. 

Rather than investigate the possibility of making changes to this functionality, I've started a poll (I promised a player I would) to see what people want. If it turns out the majority are in favour of keeping it, then we should look at what could be changed or improved upon.

A poll has been created: https://forum.sa-mp.nl/showthread.php?tid=33019

**Comment by mblokker** [comment]
The poll is leaning to keeping the feature as it is. However, some people have stated that a cooldown feature or blocking of headshots in duels is wanted. Can we maybe gain some more opinions about this?

**Comment by LVPJoe** [comment]
We're very unlikely to address this issue in the foreseeable future. A new issue will be filed if this changes; file a new issue if you feel strongly that this should be reconsidered.
