### ISSUE TITLE
Attackers have no armour in Robbery 

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#178]
Those defending in Robbery spawn with armour, but those attacking do not. Both teams should get armour in my opinion  to create a more fair match.

**Comment by mblokker** [comment]
However, a fair match would suggest a fair DM match. Attackers don't really have to DM since they can run around as rats and punch their way through players to rob the casino. The defenders, on the other hand, can only defend by killing the attackers (who are running in all directions).

I think that if you grant attackers armour, the defenders won't be able to kill attackers at all.

**Comment by ghost** [comment]
Fair point! 

I wondered if this might be a bug, but what you're saying does make sense, and I agree!

**Comment by mblokker** [comment]
Thanks!
