### ISSUE TITLE
Liberty City Issues

### ISSUE THREAD

**Issue by LVPJoe** [LVPlayground/playground#205]
As we all know, Liberty City is not solid outside of the area immediately surrounding the bistro. If a player uses a ramp to jump outside, they get stuck in the land of nothing as they cannot do /kill in an interior, and either need to tp (hopefully they have money) or log out for over 10 minutes to respawn elsewhere.

**Comment by ghost** [comment]
I question whether it's worth keeping this feature.

I hadn't really looked at it much until seeing Github case, but I see a few issues:
- it doesn't seem possible to exit the location menu, you must choose a location. We shouldn't force players to interact.
- I just tried using the feature a couple times, each time I was presented with: _There are no flights departing right now! Try again later._
- Liberty City seems unstable for the most part, players will fall through the roads for example. 

And finally, like you say, Liberty City is classified as an Interior and as such, commands are blocked.

**Comment by LVPJoe** [comment]
Perhaps in the future with a new interior handler, we could block off the exit at the back of the kitchen with an object, and use the interior as if it were an upscale restaurant/bar in LV. I agree that it's current value is minimal, but could provide for another nice location for people to spend time when not dming in the future with more protections.

**Comment by ghost** [comment]
If no one objects within the next couple days, I would like to remove this.

Here a few recent examples of players taking a flight to Liberty City, and leaving the game in a matter of seconds because they can't figure how to get back to the main world. 

> [11/01/2017 - 17:20:45] *%Nowani:%#lvp.echo* *** Lazar_Prodanovic (Id:23) has taken a flight to Liberty City.
> [11/01/2017 - 17:21:53] <%Nowani> [23] *** Lazar_Prodanovic left the game (leaving).
> 
> [11/01/2017 - 13:13:43] *%Nawoni:%#lvp.echo* *** loyd (Id:16) has taken a flight to Liberty City.
> [11/01/2017 - 13:13:53] <%Nawoni> [16] loyd: :leave
> [11/01/2017 - 13:14:17] <%Nowoni> [16] *** loyd left the game (leaving).
> 
> [11/01/2017 - 10:29:17] *%Nowoni:%#lvp.echo* *** Vedad (Id:10) has taken a flight to Liberty City.
> [11/01/2017 - 10:29:35] <%Nowoni> [10] *** Vedad left the game (leaving).

It is possible to get out but it's not elegant (involves using /taxi or /tow, after which you will be bugged) and most people will have no clue about how to do so. 

Potentially we could add some indicators on how to get back to "normal" but I see no value in doing so...there's really nothing fun or exciting about going to LC. There is a high-value property but I don't consider that a good enough reason.

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
