### ISSUE TITLE
Create another Ship in Las Venturas / AFK system

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#267]
i suggest to create another ship in LV include god mode etc .....

Location : near LVP Fight Club 

Pizzaria =====> Ship :)

and /afk for going AFK  + [AFK] tag or toggling tp with reason ("This Player is AFK now ")

and /back for going Back

**Comment by BigShem** [comment]
Hello, I don't know if I have the right to reply here but I don't really see the need to create a second ship, plus LVP FC isn't that far from the ship, and the main ship should be unique because most players fight infront of it, and /taxi 0 and /tow 0 are pretty cheap and quick commands btw.

The AFK options looks great, but I don't think players would use it.  Some players will /taxi to the ship and esc there to farm hours and cash. /afk would rarely be used.

Those are just my thaughs I might be wrong on them, let see what others think. Have a nice day :) .

**Comment by xhoogland** [comment]
About the ship:
At this moment I am thinking of, yes yet again, a complete revamp of the shiparea. Meaning to move the ship some backwards with a longer ramp, enlarge the area of no-shooting and perhaps some other interesting stuff. I indeed wouldn't like to add another ship in LV since that splits LV more which has more disadvantages than advantages, although maybe a ship in an other city or so it cool, but definitely not another one in LV. If you have suggestions, feel free to post them though. ;)

About afk:
I am still not quite sure about such a system. In the past we had one which caused some bugs which annoyed our players so much to see them leaving. As our lovely @mblokker already commented in another issue of you we do have an active, but working in the background, afk-system running.
Putting a text above someone's name could we an interesting idea, I'd like to hear others about it.

**Comment by BigShem** [comment]
I personally still don't like the idea of having two ships even in a different city, but renewing the ship would be an awesome idea.

**Comment by ghost** [comment]
@xhoogland @BigShem

about afk system  i just want something alerting players when 1 go adk 
q
and ship 1 near LVP Fight club is needed 

fight's in LVP near (The Main Ship and LVP Fight Club)

**Comment by BigShem** [comment]
The ship near LVP Fight club isn't needed at all, plus where would he insert it while I don't think there is water near.

**Comment by ghost** [comment]
You says that because You are not player now u can do /t 11 and kaboom you are there

You need to mind like fighter there

you tired on fight tothe ship is the best way to get a rest but if it's in LVP FC u can't abuse and use /taxi 0 so u need a car if u go to car u dead

so Ship is needed

**Comment by BigShem** [comment]
I've been a player longer than you so please don't say I don't feel what it is, plus I sometimes come undercover and I never needed a second boat, a simple /inf and you arrive to destination, or even /tow who has no waiting time. It would be stupid to cut LV in half with two boats. I'd rather have 8 people fighting infront if the boat than 4 in a side of lv and 4 in the other side.

**Comment by TotalEpicFailure** [comment]
I would like to jump in here and agree with Shem—a second ship-like area is certainly not **needed**. Especially not for the Fight Club. There's health pickups right there, we already have a taxi system in place to take you there, and if you need to step away, you can drive for ~5 seconds (or run for about 30 seconds) to the ship, taxi there, or just pause your game (an icon already shows up when someone is minimized/paused, the hourglass). Further, the FC is not about resting, it's about fighting. That's why the ship exists in the first place—to gather anyone who might be wanting to take a bit of a rest (and listen to the radio).

The ship was always a unique piece of LVP—I'm of the mind there should be only one (as again, no real **need** for another, even in another city). Also, with regard to the AFK system, @xhoogland already mentioned that we have one working in the background (which is working perfectly, in my opinion)
