### ISSUE TITLE
/rampcar is not a vehicle!

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#275]
So the spectacular Infernus+ramp car that has just been added, while very fun, is not recognized as a vehicle for /v or /fixvehicles purposes. Which can lead to quite a few of them lying about. I think it might be useful to have the /v command work with /rampcar, at the very least to unspawn any ludicrous amount!

**Comment by xhoogland** [comment]
At this very moment this vehicles is way differently created then our other vehicles. Rampcars are all handled the javascript-side where the pawn-part of our gamemode has almost no knowledge of.

Since I have heard @RussellLVP's next project is vehicles in javascript, it should be solved all in once! Right now the respawn is set to 3 minutes for the vehicles created by javascript, which is only the rampcar.

**Comment by TotalEpicFailure** [comment]
Ah, so there is an automated respawn already at work (and it seems even more work thereafter)! Excellent, thank you!
