### ISSUE TITLE
Incorporate more colors in /my color

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#327]
At the moment our color selection seems fairly limited as opposed to having the full palette of SA:MP colors. While the entire library of colors might be a bit silly to have as part of the selection, why not add a bit more diversity by making the current color boxes smaller and adding more (thereby allowing the selection box to remain the same size)?

**Comment by RussellLVP** [comment]
Since colours in SA-MP have four channels, _the full palette_ means 4,294,967,296 colours. That are quite some boxes.

We could make a two-stage colour selector: first you select the base colour (e.g. red), then you select the shade (e.g. light red). It'd be relatively easy to have either 256 (4x4 picker) or 625 (5x5 picker) colours available in the selector.

**Comment by TotalEpicFailure** [comment]
Well, I certainly don't think having the _full palette_ is necessary! But I do absolutely love the thought of having a color selection. A 5x5 picker allowing for so many options (but, you know, not 4 _billion_) would be amazing!

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
