### ISSUE TITLE
The ability to silence Gunther? (/show messages)

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#389]
As we know, Gunther, the helpful chap that he is, does these every 5 minutes:

[19:26] _%Noweni:%#lvp.echo_ **\* Gunther (Id:6) has done /show beg.
[19:31] _%Nuwini:%#lvp.echo_ **\* Gunther (Id:6) has done /show weaps.
[19:37] _%Nuwani:%#lvp.echo_ **\* Gunther (Id:6) has done /show forum.

Would it be possible to implement a /settings option to disable these at the player's discretion? Similar to how we can disable News Messages with /settings newsmsg off and Show Messages with /settings showmsg off. 

I for one would be a big fan and user of this feature - anything to help clean up the chat, especially during busy periods, is much appreciated.

**Comment by TotalEpicFailure** [comment]
I am uncertain we want to have a setting for players to disable announcements made by crew members. Due to Gunther using `/show` commands, perhaps we can make `/show` a possibility to disable in lieu of completely removing a crew member's ability to make server-wide announcements. I am not sure if this is more difficult to implement, but I feel this encompasses the spirit of the suggestion without negating the usefulness of `/announce`.

Just my own two cents! ☺
