### ISSUE TITLE
/property [id] goto

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#40]
/property [id] goto is for crew members, and teleports them to a chosen property. It doesn't take vehicles into account, though. If you happen to be in a vehicle, and use this command, your vehicle will be left behind. This isn't a command I personally use much, but when I do, it can be frustrating. 

Can this be adjusted?

**Comment by ghost** [comment]
@GrannyLVP 
I'm still wondering when Crew members are going to start focusing on what really is important. I made the LVP command document to keep track of things and keep others up-to-date also. One of the things I pay attention to is that the Crew members have what they need in order to perform correctly.

What I focus on and what I will keep focusing on for the next few years is our players. Crew members have access to everything and can come up with many ways to have fun by using special commands for example. On the other hand, some of our players gets bored because almost everything is either bugged or limited so they look for fun elsewhere or by installing mods that's not allowed and get a ban of course.

It is important for us to be on the same page especially if you're active and taking part in most of these things. You don't have to agree 100% with me, but you need to understand why **I** monitor trac along with Beaner, and now GitHub. I can assure you that there will be 50+ issues if I decide not to give a damn and LVP heads south again. Because the structure of this server will be changed, things will be removed, by those who knows little to nothing. It's like in one of your tickets you suggested the command /stats to be removed while this is very useful. We could easily see missing vehicles/atm's, or even a heads up that we are close to having ~1.300 vehicles which is the limit given by Russell. 

We were running a very small team back then, and today we still lack developers, but we were active and important information was shared among us with certain information forwarded to Crew members. Things went faster and if you're planning on staying then you can tag along and always ask those you're working with. What one developer might not know, another does, and so on. I try my very best to simplify things because we do not have much people that can do stuff and I don't want developers to ask 20 questions before thinking of doing something or to demotivate them.

Now you have an idea where Beaner and I stand and even if we might not be active, expect us to comment. Even when somebody is just trying to "better" or "improve" the server, and especially if you're a new player or Crew member. We are the bridge that knows pretty much everything, we are the last ones to get a taste of the old stuff and could actually tell you what made things so boring now. And the last ones who cares to do some work where most sticks to the forum and make suggestions. Though this might sound strange, we probably have a better idea than managers or developers bout certain things. That's why it's never a good idea to go around us to get approval without hearing our 2 cents first.

While this could be an easy and quick work for developers, I still felt the need of saying what I said above though at the end of the day it's up to developers. But I'm sure they will say to themselves: pshhh, this is minor and can be dealt with later. Though they should comment, but that's where I kick in most of the times. And I've seen this happened a lot. Something is working properly, it gets adjusted though it's not needed and later a reply that it isn't working properly - time wasted.
Bugs are bugs of course, but then I be pissing some people off if I start making issue's or suggestions to adjust features w/e. 

This is with no intention to demotivate you and you've been doing a great job. But note that I have a list of bugs/features I keep to myself while in hope of [these](https://github.com/LVPlayground/playground/issues)  important ones to be solved or implemented.

**Comment by mblokker** [comment]
I think what striker's trying to say: spawn a new vehicle when you get there and live with it. Takes a few secs extra.

I do agree that tickets like these demotivate. Best if you fix things like these on your own. I read somewhere that you're learning Pawn, awesome! These kind of bugs are easily solved by looking at other cmds/features and copying what they have. That's also how you learn Pawn the fastest. I would say: give it a shot :)

**Comment by ghost** [comment]
@strikerLVP 

I disagree with your points (that of course doesn't mean you're wrong, we all have our opinions) but this isn't the place to discuss development as a whole (this is a specific case/issue, and should remain specific to said case) and so I'm not going to comment further here. I'm more than happy to, but this isn't the place to do so. 

Seeing as you're always "so very busy" as per what I've seen on IRC many times, can you blame me for not approaching you about anything LVP related? No is the answer. 

Apparently you've forgotten about the Staff roles clarification thread as well. 

I'll close this out. I don't expect to see it re-opened.

**Comment by RussellLVP** [comment]
The order of constituencies adhered to by Las Venturas Playground prioritizes players over staff. Any issue that affects players has per definition more priority than issues that only affect staff. (Note that this deliberately does not account for the severity of an issue.)

Even when only considering issues that only affect staff, this would score very low on the priority list.

But does that matter?

No. I would much rather have too many issues filed than too few. The benefit of having too many issues is that we _know about them_, and can consciously make a decision on whether or not we want to fix it. Not knowing about an issue in the first place mandates the decision - we won't.

A second important argument are tokens. If somebody does a great job at improving the community, regardless in what way, is it fair to spend some time solving the issues they run in to? I think it's a great way for us, as the community, to say thank you.

Are issues like these demoralizing? Only if you consider large quantities of issues to be demoralizing. Perhaps that is the problem we should try to solve instead, which we can attack using clear use of labels and documented search queries.

Fixing this issue literally takes me less than five minutes, but I'm unfortunately unlikely to get to it soon. I like five minute issues because they're easy to do in between other work.

**Comment by RussellLVP** [comment]
Fixed!
