### ISSUE TITLE
/afk for admins.

### ISSUE THREAD

**Issue by BigShem** [LVPlayground/playground#413]
A /afk mode for admins would be cool to show that they aren't on duty when they are afk or esc. I've seen some players complaining after finding out that I'm online using /admins, but what they didn't know is that I wasn't even playing! Obviously it would show it via /admins .

**Comment by TotalEpicFailure** [comment]
Administrators who go away from keyboard for an elongated period of time should simply leave the server so that there is no confusion and reports can be successfully transmitted to the crew channel on IRC (Saber would also have to be reconfigured to work with this new command). We should not be adding a feature that is easily fixed by a simple action on our end—in this sense, we are over-analyzing and over-complicating a nonissue.

**Comment by r2dsleep** [comment]
Another great idea by Shem. When people spot a hacker, they use report, and if the admin is AFK, they get pissed and use /report even more. This command should be added and there should be an "AFK" sign standing next to admins nickname when someone uses /admins (if the admin is online, of course).

**Comment by TotalEpicFailure** [comment]
Sleep, please see my response above: administrators _should not_ be online (or at the very least, logged in as one) if they are not actually playing. This is done for a multitude of reasons, but it is a well-established guideline for crew members. It is far too trivial for crew to _leave the server_ in lieu of creating a feature (and thereby excuse) for this behavior we are attempting to curb.

Yes, there are times when crew members are not readily available, and in those instances it is unfortunate to see a report go unanswered. However, utilizing IRC and attempting to find an online admin is a wonderful strategy you should continue to do (like the PMs you have sent me in the past!) in addition to the usual `/report`.
