### ISSUE TITLE
Closable reports.

### ISSUE THREAD

**Issue by BigShem** [LVPlayground/playground#414]
If we want to take care of all reports, I suggest adding a new report system that would save reports, for example if some one reports, his report would be #1 and if someone after him reports after him it would be #2, obviously an online admin would take care of the #1 report, when it's done he would have the possibility to close the report, and due to the first report been solved, the old #2 would change to #1 so the admin can take care of it. If we have 2 admins, a /reports command would be useful to show reports still not solved so they can take care of them. This is just an idea and I'm sure many of you might disagree, but still I feel like it might work.

**Comment by TotalEpicFailure** [comment]
While I love the idea of a ticketing system for reports, it would be better suited for a larger population. At the moment, I would very much argue that we simply do not get so many reports that it is worthwhile to implement a new feature. If there are two administrators online and there are suddenly three reports to take care of, communication is key: "I'm on ID 3, will look at ID 10 in a sec." I think this is a complex solution to an issue that LVP does not have, or runs into very rarely.

**Comment by BigShem** [comment]
We might not have a big population indeed, but when we have around 40-50 players the chat goes fast, really fast, specially with all the notifications admins get. Plus reports and admin chat have same color which make it way harder to notice. Indeed some times we get reports that make nearly no sence like the famous "hak de juego", and most players spam chat with "id 10 hack pls banned". It would help us to avoid all this spam and take care of reports more quickly, well I hope so.

**Comment by TotalEpicFailure** [comment]
Reports are the same yellow color as the admin chat so that it is easily read and not so easy to ignore. Further, as soon as a player gets reported, there is a delay in when that player can be reported again. In addition, we even have a function that should be utilized by in-game crew when players are reporting in the main chat (https://github.com/LVPlayground/playground/commit/d7b35b5dd90644988618b5538fbafe50020097d3). 

I would recommend setting one's `/pagesize` to 20 if the server's population is causing more to happen in the chat—10 is far too little, I would agree, but I also believe that using one's settings to properly minimize chatter and background noise is key in this situation.

**Comment by r2dsleep** [comment]
This is a great idea. Maybe you should also add a command /accept report ID, and when you do that, a player that used /report gets the information message that certain admin is watching reported player.

**Comment by TotalEpicFailure** [comment]
Sleep: Administrators will nonetheless get bombarded with repetitive and impatient players, whether that be in the form of demands of immediate ban, constant reports (usage of admin chat or in the main chat itself), or otherwise.

Is there a legitimate reasoning as to how this is a problem as it stands? Player_A reports Player_B due to suspicious behavior and an administrator will take care of it. I apologize, but creating an extra step for administrators in order to handle reports will likely take more of a delay thereby leading to more impatience from the reporting party. I fail to see how a simple PM to an administrator (worst case scenario) is that much trouble for the player.

I would also like to point out that, again, _patience is key_ with reports. `/report` -> administrator will watch (sometimes this takes a few minutes, even longer!) -> _maybe_ a kick/ban. Regardless of how these steps get sliced, there will always be an unhappy party—whether it be the reporter for not seeing "the cheater" banned, the suspected player due to being forced to leave our beloved server, or even the administrator for not being able to abuse players with purple dildos because of a report to which they had to attend. It all comes down to the following: there are simply _not that many reports_ to warrant the implementation of a queue.

(By the way, thank you for your time in commenting/suggesting, Shem and Sleep—while I disagree with this particular concept, I love that you two are being involved in direct suggestions/feedback! Stay vocal! ☺)

**Comment by r2dsleep** [comment]
Maybe you should also forbidden reporting the same player twice, or using the /report command. You maybe should add 2 minute cooldown after using report again.

**Comment by TotalEpicFailure** [comment]
![gta_sa 2016-11-01 14-59-31-54](https://cloud.githubusercontent.com/assets/21077320/19903384/dc655064-a044-11e6-881d-46416a07ebaa.png)

We already do this, Sleep! ☺

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
