### ISSUE TITLE
Removing rights issue

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#42]
I was a little busy and half in-game, half doing other things, and so I took my crew rights (rather than left) as I figured that way, @ messages would end up in the .crew IRC channel rather than just in-game. 

I've tried two methods:

IRC: !taketempadmin [ID]
Ingame: /p [ID] takeadmin

Each time, my name was removed from /admins and double clicking my name on TAB showed my Level as "Very Important Player". So the gamemode seemed to recognize that I was no longer an admin, good, fine, no problems here.

The issue is, IRC (Saber?) does not seem to recognize that:

---

[18:34] <%Nuwani> [10] **\* Granny joined the game.
[18:34] <%Nuwani> [10] **\* Granny has logged in.
[18:34] _%Nuweni:%#lvp.echo_ **\* Granny (Id:10) has taken admin rights from Granny (Id:10).
[18:37] @Granny !ingamecrew
[18:37] <%Saber> \* Ingame crew (1/42): Granny (ID: 10)

---

If this is considered an easy fix, it'd be great if it could be fixed up.

**Comment by BeanerLVP** [comment]
From what I understand, /p takeadmin is only used to temporarily revoke moderator/administrator rights in-game. It is _temporary_ in case of crew accounts as well. The level of your account still remains 'Administrator', which is why reports don't get forwarded to #LVP.Crew.

If you wish to remain in-game with your main/crew account and want reports to be forwarded to IRC at the same time, you'd have to manually set your level to 'Player', use the !updatecrew command, and then go in-game. You'd have to follow a similar procedure to get your rights back.

It's probably not worth the hassle. Just use another account or nickname when you feel you don't have time to handle reports, and others can view them on IRC.

We've just got 1 active developer, so I think it's best not to worry about things like this for now. Don't take it the wrong way. I felt the need to point this out since this is more of a feature request than a bug.

**Comment by RussellLVP** [comment]
Please file all the bugs. Always, even when they have super low priorities like this one. Adding labels accordingly.

**Comment by RussellLVP** [comment]
I wrote down my stance on this here by the way: https://github.com/LVPlayground/playground/issues/40#issuecomment-152163371

**Comment by debuggest3** [comment]
Saber gathers its information from interpreting the messages from #LVP.echo. However, I was not aware that the "take admin" command could also be used on permanent crew. This means that those messages are only applied to the list of temporary crew which Saber keeps track of.

Of course it's possible to change this, but the "take admin" commands have rarely — if ever — been used to remove the rights of permanent crew and I wonder if it's worth the effort of adding support for this in Saber.

**Comment by ghost** [comment]
I've added some additional reasoning behind this, here: https://forum.sa-mp.nl/showthread.php?tid=32655

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
