### ISSUE TITLE
Implement brief anti-spawnkill feature

### ISSUE THREAD

**Issue by TotalEpicFailure** [LVPlayground/playground#425]
Years ago, LVP had 3 or 5 seconds after spawning where a player was invincible (spawn-weapons/armor would spawn after this period). 

This prevented spawn-killing in an effective manner, and (assuming this is something we want to change) I am proposing we re-implement this old feature.

**Comment by ghost** [comment]
+1 - however I would be tempted to set this to 15-30 seconds, which would be sufficient time for someone to grab a car and at least have a chance to escape. 

I just witnessed a player getting repeatedly spawn killed at their house by a gang, the player had no chance at all other than potentially waiting for the gang to get bored.

Another player suggested that players should spawn inside their house rather than outside. This doesn't sound like a bad idea, but I really have no strong preference.

**Comment by ghost** [comment]
> Another player suggested that players should spawn inside their house rather than outside. This doesn't sound like a bad idea, but I really have no strong preference.

i think it's a good idea but Spawn Protection Sloved this i think :)

**Comment by RussellLVP** [comment]
We're declaring a bankruptcy on old PRs and issues, so I'm going to close this out. Thank you for your report and contribution!
