### ISSUE TITLE
Kick/Ban with no reason under !why

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#43]
This is the same as Issue #4 though I'm opening up a new case per Russell's notes, as this problem is on-going:

Luka_Bulum was kicked today, and had been playing for quite some time prior to this, typing messages in the chat as a normal player would, and then, all of a sudden:

[15:50] <%Nuwini> [27] **\* Luka_Bulum left the game (kicked).

Checked out !why, no results:

[15:50] @Granny !why Luka_Bulum
[15:50] <&Nuwani> **\* No items found for player Luka_Bulum.

I must stress that this isn't the first instance in which this has happened, I've seen this happening on numerous occasions.

**Comment by ghost** [comment]
Another example just happened:

[10/01/2016 - 16:13:05] <%Nuwuni> [32] **\* Dawood joined the game.
[10/01/2016 - 16:13:05] _%Nuwini:%#lvp.echo_ IP Address Dawood (Id:32): -removedip-
[10/01/2016 - 16:14:53] <%Nuwini> [32] **\* Dawood left the game (kicked).

samp@play:~$ grep Dawood /home/samp/playground/server/server_log.txt
[16:13:09] [join] Dawood has joined the server (32:-removedip-)
[16:14:57] [part] Dawood has left the server (32:2)
samp@play:~$

As with before, no reason under !why, nor ingame or IRC.

**Comment by jadegraaf** [comment]
Could this have to do with the 'ackslimit' value in the config?
"The default 'ackslimit' is raised from 1000 to 3000. Some servers had problems with players being erroneously kicked with an 'ackslimit' of 1000."
http://forum.sa-mp.com/showpost.php?p=2989045&postcount=1

Maybe this keeps happening to us even though we're using the default of 3000 (If I'm not mistaken)

**Comment by ghost** [comment]
I just did some more digging:

http://pastebin.com/raw/BbdW7xzQ

Censored the user's IP for privacy reasons.

@oostcoast - our ackslimit is 5000.

**Comment by xhoogland** [comment]
What I see so far is that these kicks are highlikely done by SA-MP. I scanned our gamemode on Kick's (since we don't use SA-MP's Ban(Ex)) and ->kick's where I see that they are respectively are used for NPCs and players where in the last case it is logged. I doubt it is also a stuttering db-connection.

**Comment by mblokker** [comment]
See: https://wiki.sa-mp.com/wiki/Advanced_Server_Controls
"The above four limits/counts are just made to avoid several tools which can attack any SA-MP server by freezing it or crashing. So, simply, just set them according to your server. The default values are default, if you see any wrong kicks, just increase the values as soon as possible so that the innocent players won't get kicked by it. More info: http://forum.sa-mp.com/showpost.php?p=2990193&postcount=47"

After these months of testing I think it is safe to say it's because of said limits in the server.cfg. We could try to make these as accurate as possible, but it will probably be hard to avoid these kicks.

**Comment by xhoogland** [comment]
Those are recently changed seen in https://github.com/LVPlayground/server/commit/ff9c202a60019735bc5b0c41543ee8af96c184a4 although I don't know if these are the actual changes on the production server!?

**Comment by ghost** [comment]
@Xanland - those changes are live on the production server

**Comment by mblokker** [comment]
I think we can come to the conclusion that players will only be kicked by the native Kick() function from SA:MP. If they were banned, the samp.ban file should list their IPs, since they were not banned by our own ban-system. We should keep an eye on this file, since we don't use it (it is empty at the moment).

We can't intercept these random kicks, and in addition, they are actually meant to protect our gamemode. One way or another the values in server.cfg led to this kick. So, let's close this out and keep an eye on the samp.ban file.
