### ISSUE TITLE
Should announcement filters affect IRC?

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#558]
Hey @OttoRocket-LVP -

I was very confused just now why my admin notice wasn't showing up on IRC, while it did show in-game. Tracing the code, I found that a condition in `announce_manager.js` blocked it.

I've re-enabled it for my own sake, as I often use this for testing: https://github.com/LVPlayground/playground/commit/e90a2bed601081b945233872c565d9f98a22b6e3

Let's use this to discuss however. Would we ever want to _not_ send messages to IRC?

Since we can't personalise that per administrator, my guess is that you were thinking about a global "turn announcement on or off" switch. I wonder if those should be the default values of the per-player settings instead? I think of IRC kind of like an info-dump where we share everything.

Thanks,
Russell

**Comment by OttoRocket-LVP** [comment]
Hey @RussellLVP, 

Thank you for your feedback.

I've made it so that you can enable or disable certain message using /lvp settings.

This means we can add announcements to e.g. /boost or other functionaities that we don't deem useful right now. We can then choose to show or not show announcements where the demand changes.

Managers can change the settings using /lvp settings.

**Comment by BeanerLVP** [comment]
> Let's use this to discuss however. Would we ever want to _not_ send messages to IRC?

> I think of IRC kind of like an info-dump where we share everything.

I agree with @RussellLVP 

I'm strongly against not sending **all** notices to IRC. In my personal expierience, #lvp.echo logs and certain notices in #lvp.crew have proven incredibly useful in finding specific information & dealing with certain situations over the years, especially when various bots were offline/broken or when management members weren't available. This is mainly why I still keep backups of all the logs I've had since 2012, and continue to stress the importance of certain notices (as seen in ticket #532).

For instance, dealing with issues like command or power abuse is a lot simpler when we have the logs to investigate and prove it. 

Thankfully, we have a stable version of Nuwani now, but let's keep the trend going and share everything on IRC.
