### ISSUE TITLE
Recently created houses don't have labels

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#566]
- All the houses created after some point in past, don't have any labels. There is only a marker, name of the house & name of the owner won't show.

**Comment by Specifer** [comment]
My particular house is a casualty of this bug too from  1/3 house .

**Comment by SophiaLVP** [comment]
I though a server restart can fix that problem, no?

**Comment by DeerHunterLVP** [comment]
> I though a server restart can fix that problem, no?

No.

**Comment by Specifer** [comment]
I don't know why this happens . In staging it's absolutely fine , I don't know why only some houses don't have labels and some do . Do you have any explanation for this @RussellLVP or @OttoRocket-LVP or @xhoogland ?

**Comment by RussellLVP** [comment]
There currently are 1,241 house locations on the server, while SA-MP only supports 1,024 text labels.

Two possible solutions:
  1. Start streaming the text labels, which is the right long-term solution,
  1. Decrease the number of house locations on the server.

Houses should probably expire after some point, because the server shouldn't become a graveyard. Of the 1,241 houses, 1,125 are occupied (91%). Of the occupied houses, 319 (28%) of owners has been online in the past year, 510 (45%) in the past two years, and 63% in the past three years.

I think it's entirely reasonable to expire houses. We could re-use the requirements we use for gang zones:

https://github.com/LVPlayground/playground/tree/master/javascript/features/gang_zones#what-constitutes-an-active-gang-member

If we do that, then we'll be left with 354 houses, just over 31% of what we have today.

**Comment by xhoogland** [comment]
Looks good to me! Imo people should be aware of an expiration or so in case the buy the house? It costs money and stuff. ;)

**Comment by RussellLVP** [comment]
I feel like this should probably get broader discussion, so I've moved it to the forums:
https://forum.sa-mp.nl/thread-35198.html

**Comment by SophiaLVP** [comment]
Look, I don't know if I'm liable to say but houses that are located at an unrealistic places should be removed (I'm referring to the houses that are built underneath water/oceans, flat rooftops other than exceptional cases, on the ship area where there's no point of having one). That will also free up a lot of space. What do you think?

**Comment by Specifer** [comment]
I'm sure that those houses are favour for important people that helped with LVP for a long time . Plus the underneath water house it's kind of epic though . And as per Russell's detailed expected data would be 354 houses left which is more than enough space ..

**Comment by DeerHunterLVP** [comment]
I agree with Specifer, those type of houses that are created in unusual places for me are the funniest. It's fun to see how far can players go with their imagination, and some ideas are extremely creative, original. For me personally, this is the best thing about house system anyway.

**Comment by RussellLVP** [comment]
Hi all -

For now I've changed text labels to stream, per commit https://github.com/LVPlayground/playground/commit/633f2687228e0024ee43739c33ec3c505e20d253. Let's discuss the discussion about whether to keep houses or not in parallel.

Thanks,
Russell
