### ISSUE TITLE
Reaction-tests not updating

### ISSUE THREAD

**Issue by DeerHunterLVP** [LVPlayground/playground#611]
- For some reason reaction-tests won't update in our stats during one gaming session. One has to relog in order to get this number updated.

**Comment by BeanerLVP** [comment]
I can confirm this. I tested it on the staging server with a 10 second interval between reaction tests.
The right count is displayed in the message "......they've won X times before", but reaction test wins under /my stats doesn't get updated until the user relogs.

**Comment by RussellLVP** [comment]
We are working on moving more of the account data in JavaScript, which recently happened with reaction tests. Therefore the Pawn code, which shows the stats dialog, doesn't actually know the latest data. This is something that will be fixed in time, specifically when `/stats` moves to JavaScript too.

Until that point I don't think we should implement a work-around, as that'd be quite fragile. Let's keep this broken for now, and have it be fixed when `/stats` & co. move to JavaScript.
