### ISSUE TITLE
Original ban duration gets modified upon unbanning

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#625]
If a user is unbanned by an administrator before the time it is set to automatically expire at, the original ban duration in the log gets modified to the time the player remains banned for.

>  !why test22
<Nuwani> *** Player log for test22 (13 items) - https://profile.sa-mp.nl/bans/test22
<Nuwani> [2020-05-22 16:33:42] (ban by Beaner): Testing (-IP-, **_30 days_**)

> !unban test22 Unbanned
<Nuwani> *** Player log for test22 (14 items) - https://profile.sa-mp.nl/bans/test22
<Nuwani> [2020-05-22 16:35:13] (unban by Beaner): Unbanned
<Nuwani> [2020-05-22 16:33:42] (ban by Beaner): Testing (-IP-, **_1 minute_**)

The originally specified duration should never be modified. The date and time stamps are sufficient to determine the actual period of a ban if a user is unbanned prematurely.

Edit: This info also needs to be changed in error messages, such as:

<&Beaner> !ban ip -IP- test22 7 Testing
<Nuwani> Error: This IP address ban is already covered by test22 (-IP-, **23 minutes ago by SexyMoroccan**).

!lastbans is probably the only command where displaying the elapsed time is appropriate.

**Comment by RussellLVP** [comment]
Administrators could note the remaining duration of the ban while issuing an unban. I think that would be good practice anyway: "Reducing 30 day ban to 14 days because A, B and C".

This is how bans have worked for more than a decade now. We simply don't keep the original information, because the database format does not allow for it to be stored. This _could_ be changed, but would be a fair amount of effort as the SA-MP server, Nuwani and the website all have to be updated to understand the new format. I personally don't think that's worth it, particularly because an easy solution is available.

**Comment by BeanerLVP** [comment]
> This is how bans have worked for more than a decade now. We simply don't keep the original information, because the database format does not allow for it to be stored. 

I'm sorry, but I don't understand this because the specified duration while issuing a ban was never modified in the logs, even after an unban. If I banned someone for 7 days and manually unbanned them in 3, the log would still display 7 days, and the unban note above it would determine the actual period of the ban. 

However, I realize that this process is actually automated now and isn't a bug. It makes sense to keep logs of the actual ban period anyway, and not what an administrator originally specified.
Please disregard the changes I originally proposed!
