### ISSUE TITLE
Remove the 'Issued by' column from in-game player records

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#628]
Players can find the identity of undercover administrators via this method. When it comes to players viewing their own records, the _Date_, _Type_, and _Reason_ columns should suffice.

Another suggestion is to replace the administrator command **/account [id]** with **/why**, to be consistent with IRC and make it easy to remember (like with /lastbans). Also, the 'Issued by' column can remain via this command for administrators who wish to view other players' records in-game.

**Comment by RussellLVP** [comment]
Let's take a step back first and rephrase the _problem_ in this issue: the undercover identities of administrators could be revealed to through the `/account` command.

Concretely, say that administrator "Bob" decides to investigate undercover as "Alice". We want to protect the name "Alice", not "Bob", because players have other ways of obtaining this information already so there would be little point. Correct?

One possible _solution_ could indeed be to remove the column. I think that this transparency and accountability is important, and, as you can imagine, care quite deeply about keeping it.

In order to make a proposal here, I would like to better understand the following flow:

  1. "Frank" breaks one of the rules, and gets banned by "Alice", who actually is "Bob" undercover.
  1. Frank files a ban appeal on the forums.
  1. Who replies?

**Comment by BeanerLVP** [comment]
>     1. "Frank" breaks one of the rules, and gets banned by "Alice", who actually is "Bob" undercover.
>     2. Frank files a ban appeal on the forums.
>     3. Who replies?

The idea isn't to keep a random/undercover name from being revealed a later time, like when it comes to ban appeals. Bob, of course, should handle the appeal & Frank deserves to who know banned him.

The intention behind this request was to hide identities while a crew member is online and actively investigating a bunch of players, so that one player who gets kicked for something doesn't rejoin and inform others about who is online. But I now realize that this doesn't really matter. I guess I didn't quite think about this clearly, since kicks/bans already indicate the presence of a crew members, and their undercover nicknames/IDs are not revealed anyway.
