### ISSUE TITLE
Vehicle system overhaul

### ISSUE THREAD

**Issue by RussellLVP** [LVPlayground/playground#700]
We're rewriting the vehicle system for LVP 48, to simplify the entire system, improve our streaming performance and fix many of the existing bugs. As part of this, we're revising the existing feature set, which means that various things have been deleted.

This bug contains an overview of what's changing, as well as pending action items that have to be fixed before release.

## Deleted features
  * `/v pin` and `/v unpin`, which is low-level functionality that works automagically.
  * `/v optimise`, which is useful, but similarly low-level and done automatically.
  * `/v density`, which is, while informative, not really required in practice.
  * `/v color`, which is hard to use, therefore rarely used, and would be better suited by supporting paint jobs etc.
  * `/v access`, which is important in theory, but in practice has only been used for campers in CP's Los Santos zone.
  * `/lock` and `/unlock`, which are useful, but have too many dependencies the way they work now

## Added features
  * **Iterative streaming**, which means that the quality and balance of available vehicles will improve.
  * **Threaded streaming**, which means that streaming no longer occurs on the main thread, which will reduce lag.
  * House vehicles and ephemeral vehicles will now have personalised number plates.

## TODO
  * Consider adding `/lock` and `/unlock` back.
  * Consider adding `/v access` back.
  * Consider adding `/v color` back.

**Comment by RussellLVP** [comment]
Saving vehicles has also been fixed, so let's close this.

**Comment by EPIC-striker** [comment]
Russell, 

Sorry for being late with these. 

There's an intermittent issue where your vehicle disappears when you're in the /tune shops. 
This would bug my map and the tune menu would be stuck on my screen until I relog. However, since my session is restored upon reconnecting, I will spawn again in the shop. 
On one occasion as soon as I entered the shop, the vehicle disappeared. 
Perhaps the automatic resetting of the vehicle layout is the cause here?

/v save 

There's no error message when this is used and the car would disappear right away. 
 
![sa-mp-000](https://user-images.githubusercontent.com/35706739/85233733-a3297d80-b3d6-11ea-8ae3-32e40fe67c36.png)

**Comment by RussellLVP** [comment]
Would you mind opening a new issue for the tune shop problem?

`/v save` has already been fixed.
