### ISSUE TITLE
Display the common serial warning under !serialinfo

### ISSUE THREAD

**Issue by BeanerLVP** [LVPlayground/playground#719]
I really like the new feature of !whois where it displays the "(common!)" text for shared serials.

 !whois Felix_Estrada
<Nuwani> Results: Felix_Estrada (26x, -IP & serial- **(common!)**, 3 hours ago)

It'd be quite useful to have the same text implemented for common serials that are looked up using !serialinfo, so that crew members can make informed decisions about whether or not a serial _really_ requires banning.

How are we determining shared/common serials? Does it have anything to do with the list I've compiled in the crew forum?

**Comment by RussellLVP** [comment]
Fixed.

> How are we determining shared/common serials? Does it have anything to do with the list I've compiled in the crew forum?

We have 126,859 unique serials in our database. I've added every serial that's been used by more than a hundred distinct nicknames to a table, which now has a selection of 77 serials. For in-game purposes we're considering all serials that have seen more than 250 nicknames, because we still had a bunch of false positives. That gave us the following list:

Serial     | Nicknames
-----------|-----------------
1715132128 | 4636 nicknames
2447290664 | 4314 nicknames
554591146  | 2768 nicknames
1965940595 | 2656 nicknames
3792180276 | 1818 nicknames
1441804321 | 1388 nicknames
3923073342 | 744 nicknames
1915947708 | 712 nicknames
1227933814 | 647 nicknames
2564387290 | 612 nicknames
668425933  | 612 nicknames
999311012  | 602 nicknames
2835325564 | 491 nicknames
3188995857 | 430 nicknames
4090639834 | 413 nicknames
1278501170 | 367 nicknames
302865275  | 357 nicknames
2456512593 | 348 nicknames
3887102064 | 344 nicknames
4099179621 | 330 nicknames
652812532  | 319 nicknames
744912328  | 319 nicknames
783018855  | 312 nicknames
3002894118 | 297 nicknames
3744631145 | 275 nicknames
3265794030 | 274 nicknames
2883972882 | 268 nicknames
2101723746 | 266 nicknames
1068401045 | 265 nicknames

Note for other server owners who might come across this, we store a 32-bit hash of the GPCI rather than the full string for efficacy reasons, and also to increase clarity for our administrators.

Technically, what we call a _serial_ is a [Murmur v3 hash](https://en.wikipedia.org/wiki/MurmurHash) of the GPCI.
