### ISSUE TITLE
When leaving deathmatch lagshot is not always removed.

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#745]
Sometimes when a player uses /deathmatch leave his lag shot setting is not set back to lagcomp.

Might have something to do with lag/desync?

**Comment by RussellLVP** [comment]
I found (and fixed in 620b502e) a case that might've caused this:

```javascript
if (!teleportStatus.isApproved()) {
    // kill
} else if (player.syncedData.lagCompensationMode !== 2) {
    // reset lag comp & respawn
} else {
    // respawn
}
```

This means that if a player types `/deathmatch leave` immediately after taking damage in a lag shot mode, we _do not_ reset the lag compensation mode back to skin hit.

As mentioned, now fixed. I'm not sure if there are other fixes in #743?
