### ISSUE TITLE
Unit test: 'should enable players to win reaction tests' sometimes fails

### ISSUE THREAD

**Issue by OttoRocket-LVP** [LVPlayground/playground#757]
IF the stars allign right this unit test will fail.

[features\reaction_tests\reaction_tests.test.js:123] ReactionTests should enable players to win reaction tests: expected {FFFFFF}[0] Gunther:{FFFFFF} Porter tunnel. to include PORTER TUNNEL, but it doesn't.

It appears to sometimes apply the grammar fixing.

**Comment by OttoRocket-LVP** [comment]
Fixed in 9001e8876dfb777880711aeb373b1e9efc7e336a

However, I guess we don't want to apply grammar fixing for reaction tests?
Also maybe we should make the test pick a specific reaction test? (To avoid the randomness of the tests)

**Comment by RussellLVP** [comment]
I think this is the right fix.

Reaction tests should not be an exception. Like all other communication, they should be subject to our message and spam filters. That could indeed lead to unanswerable questions, but that'd be by design.

Reaction test verification routines already consider the possibility that something has been subject to the rewrite tool.
